address: https://test-stand.gb.ru/gateway/login 
username: Nikolai123
password: d1e074caeb
address2: https://test-stand.gb.ru/api/posts
titlee: ABOUT SWEET BREAD
descriptionn: DESCRIPTION OF SWEET BREAD
contentt: A LOT OF SWEET BREAD